Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Models/DetalleVenta.cs
using System.ComponentModel.DataAnnotations;

namespace Tienda_Electronica.Models
{
    public class DetalleVenta
    {
        public int ID_DetalleVenta { get; set; }

        [Required(ErrorMessage = "La cantidad es obligatoria")]
        [Range(1, int.MaxValue, ErrorMessage = "La cantidad debe ser un número entero positivo")]
        [Display(Name = "Cantidad")]
        public int Cantidad { get; set; }

        [Required(ErrorMessage = "El subtotal es obligatorio")]
        [Range(0, double.MaxValue, ErrorMessage = "El subtotal no puede ser negativo")]
        [Display(Name = "Sub Total")]
        public decimal SubTotal { get; set; }

        [Required(ErrorMessage = "El precio unitario es obligatorio")]
        [Range(0.01, double.MaxValue, ErrorMessage = "El precio unitario debe ser mayor a 0")]
        [Display(Name = "Precio Unitario")]
        public decimal PrecioUnitario { get; set; }

        [Required(ErrorMessage = "La fecha de venta es obligatoria")]
        [Display(Name = "ID Venta")]
        public int ID_Venta { get; set; }

        [Required(ErrorMessage = "El nombre del producto es obligatorio")]
        [Display(Name = "ID Producto")]
        public int ID_Producto { get; set; }

        // Propiedades adicionales para mostrar en las vistas
        [Required(ErrorMessage = "La fecha de venta es obligatoria")]
        [Display(Name = "Fecha de Venta")]
        public DateTime FechaVenta { get; set; }

        [Required(ErrorMessage = "El nombre del producto es obligatorio")]
        [StringLength(100, MinimumLength = 3, ErrorMessage = "El nombre del producto debe tener entre 3 y 100 caracteres")]
        [RegularExpression(@"^[a-zA-Z\s]+$", ErrorMessage = "El nombre del producto solo debe contener letras y espacios")]
        [Display(Name = "Nombre del Producto")]
        public string Nombre_Producto { get; set; }

    }

}

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Controllers/DetalleVentaController.cs
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using Tienda_Electronica.Data;
using Tienda_Electronica.Models;
using Tienda_Electronica.Repositories.DetalleVentas;
using Tienda_Electronica.Repositories.Productos;
using Tienda_Electronica.Repositories.Ventas;
using Tienda_Electronica.Validations;

namespace Tienda_Electronica.Controllers
{
    [Authorize]
    public class DetalleVentaController : Controller
    {
        private readonly IDetalleVentaRepository _detalleVentaRepository;

        //
        private readonly IVentaRepository _ventaRepository;
        private readonly IProductoRepository _productoRepository;
        //

        //Validaciones
        private readonly IValidator<DetalleVenta> _detalleventaValidator;

        public DetalleVentaController(

            IDetalleVentaRepository detalleVentaRepository,

            IVentaRepository ventaRepository, //Nuevo
            IProductoRepository productoRepository, //Nuevo

            //Nuevo validaciones
            IValidator<DetalleVenta> detalleventaValidator
            //

            //IValidator<Venta> validator
            )
        {
            _detalleVentaRepository = detalleVentaRepository;

            //tegoria
            _ventaRepository = ventaRepository;
            _productoRepository = productoRepository;
            //

            //Validaciones
            _detalleventaValidator = detalleventaValidator;
        }

        // GET: DetalleVentaController
        public async Task<ActionResult> Index()
        {
            var detalleVentas = await _detalleVentaRepository.GetAllAsync();
            return View(detalleVentas);
        }

        // GET: DetalleVentaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        //GET: DetalleVentaController/Create
        // public ActionResult Create()
        public async Task<ActionResult> Create()
        {
            //
            var ventas = await _ventaRepository.GetAllAsync();
            var productos = await _productoRepository.GetAllAsync();
            ViewBag.Ventas = new SelectList(ventas, "ID_Venta", "FechaVenta");
            ViewBag.Productos = new SelectList(productos, "ID_Producto", "Nombre_Producto");
            //
            return View();
        }

        // POST: DetalleVentaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(DetalleVenta detalleVenta)
        {
            //Validaciones
            ValidationResult validationResult = _detalleventaValidator.Validate(detalleVenta);

            try
            {
                await _detalleVentaRepository.AddAsync(detalleVenta);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;

                //Nuevo
                var ventas = await _ventaRepository.GetAllAsync();
                var productos = await _productoRepository.GetAllAsync();
                ViewBag.Ventas = new SelectList(ventas, "ID_Venta", "FechaVenta");
                ViewBag.Productos = new SelectList(productos, "ID_Producto", "Nombre_Producto");
                //

                //Validaciones
                validationResult.AddToModelState(this.ModelState);

                return View(detalleVenta);
            }
        }

        // GET: DetalleVentaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var detalleVenta = await _detalleVentaRepository.GetByIdAsync(id);

            if (detalleVenta == null)
                return NotFound();

            //
            var ventas = await _ventaRepository.GetAllAsync();
            var productos = await _productoRepository.GetAllAsync();
            ViewBag.Ventas = new SelectList(ventas, "ID_Venta", "FechaVenta", detalleVenta.ID_Venta);
            ViewBag.Productos = new SelectList(productos, "ID_Producto", "Nombre_Producto", detalleVenta.ID_Producto);
            //

            return View(detalleVenta);
        }

        // POST: DetalleVentaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(DetalleVenta detalleVenta)
        {
            //Validacion
            var validationResult = _detalleventaValidator.Validate(detalleVenta);

            try
            {
                await _detalleVentaRepository.EditAsync(detalleVenta);

                return RedirectToAction(nameof(Index));
            }
            catch(Exception ex)
            {
                ViewBag.Error = ex.Message;

                //
                var ventas = await _ventaRepository.GetAllAsync();
                var productos = await _productoRepository.GetAllAsync();
                ViewBag.Ventas = new SelectList(ventas, "ID_Venta", "FechaVenta", detalleVenta.ID_Venta);
                ViewBag.Productos = new SelectList(productos, "ID_Producto", "Nombre_Producto", detalleVenta.ID_Producto);
                //

                //Validaciones
                validationResult.AddToModelState(this.ModelState);

                return View(detalleVenta);

            }
        }

        // GET: DetalleVentaController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var detalleVenta = await _detalleVentaRepository.GetByIdAsync(id);

            if (detalleVenta == null)
            {
                return NotFound();
            }

            return View(detalleVenta);
        }

        // POST: DetalleVentaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(DetalleVenta detalleVenta)
        {
            try
            {
                await _detalleVentaRepository.DeleteAsync(detalleVenta.ID_DetalleVenta);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                return View(detalleVenta);
            }
        }

        //NUEVO
        // Acción para obtener el precio del producto
        [HttpGet]
        public async Task<JsonResult> GetProductPrice(int id)
        {
            var producto = await _productoRepository.GetByIdAsync(id);
            if (producto != null)
            {
                return Json(producto.PrecioUnitario);
            }
            return Json(0);
        }

    }
}

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Views/DetalleVenta/Create.cshtml
@model Tienda_Electronica.Models.DetalleVenta

@{
    ViewData["Title"] = "Create";
}

<h1>Detalle de Ventas</h1>


<hr />
<div class="row">
    <div class="col-md-4">

        <div asp-validation-summary="ModelOnly"></div>

        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <input asp-for="ID_DetalleVenta" class="form-control" type="hidden" />
            </div>
            <div class="form-group">
                <label asp-for="ID_Producto" class="control-label"></label>
                @Html.DropDownList("ID_Producto", (SelectList)ViewBag.Productos, "Seleccione un producto", new { @class = "form-control", onchange = "fetchProductPrice(this.value)" })
                <span asp-validation-for="ID_Producto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cantidad" class="control-label"></label>
                <input asp-for="Cantidad" class="form-control" oninput="calculateSubtotal()" />
                <span asp-validation-for="Cantidad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PrecioUnitario" class="control-label"></label>
                <input asp-for="PrecioUnitario" class="form-control" readonly="readonly" />
                <span asp-validation-for="PrecioUnitario" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubTotal" class="control-label"></label>
                <input asp-for="SubTotal" class="form-control" readonly="readonly" />
                <span asp-validation-for="SubTotal" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ID_Venta" class="control-label"></label>
                @Html.DropDownList("ID_Venta", (SelectList)ViewBag.Ventas, "Seleccione una fecha de venta", new { @class = "form-control" })
                <span asp-validation-for="ID_Venta" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn btn-primary">Regresar al listado</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }



    <script type="text/javascript">
        function fetchProductPrice(productId) {
            $.ajax({
                url: '@Url.Action("GetProductPrice", "DetalleVenta")',
                data: { id: productId },
                success: function (data) {
                    $('input[name="PrecioUnitario"]').val(data);
                    calculateSubtotal();
                }
            });
        }

        function calculateSubtotal() {
            var quantity = parseFloat($('input[name="Cantidad"]').val());
            var unitPrice = parseFloat($('input[name="PrecioUnitario"]').val());
            if (!isNaN(quantity) && !isNaN(unitPrice)) {
                var subtotal = quantity * unitPrice;
                $('input[name="SubTotal"]').val(subtotal.toFixed(2));
            } else {
                $('input[name="SubTotal"]').val('');
            }
        }

        $(document).ready(function () {
            // Inicializa el evento onchange para calcular el subtotal cuando se ingrese la cantidad
            $('input[name="Cantidad"]').on('input', function () {
                calculateSubtotal();
            });
        });
    </script>
}

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Views/DetalleVenta/Index.cshtml
@model IEnumerable<Tienda_Electronica.Models.DetalleVenta>

@{
    ViewData["Title"] = "Index";
    ViewData["TitleHeader"] = "Detalle de las ventas";
}

@* <h1>Detalle de las ventas</h1> *@

<p>
    <a asp-action="Create" class="btn btn-primary">Agregar Nueva venta</a>
</p>
<table class="table table-striped table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID_DetalleVenta)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nombre_Producto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cantidad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PrecioUnitario)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SubTotal)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaVenta)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.ID_DetalleVenta)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Nombre_Producto)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cantidad)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PrecioUnitario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.SubTotal)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.FechaVenta)
                </td>
                <td>
                    @* @Html.ActionLink("Edit", "Edit", new { id = item.ID_DetalleVenta })
                    @Html.ActionLink("Delete", "Delete", new { id = item.ID_DetalleVenta }) *@

                    <center>
                        @* <a class="btn btn-success" href="@Url.Action("Edit", new { id = item.ID_DetalleVenta})">Editar</a>
                        <a class="btn btn-danger" href="@Url.Action("Delete", new { id = item.ID_DetalleVenta })">Eliminar</a> *@
                    </center>
                </td>
            </tr>
        }
    </tbody>
</table>