Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Controllers/ClienteController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tienda_Electronica.Models;
using Tienda_Electronica.Repositories.Clientes;
using Tienda_Electronica.Services.Email;
using System.Threading.Tasks;
using FluentValidation;
using Tienda_Electronica.Validations;
using FluentValidation.Results;

namespace Tienda_Electronica.Controllers
{
    [Authorize]
    public class ClienteController : Controller
    {
        private readonly IClienteRepository _clienteRepository;
        private readonly IEmailService _emailService;

        private readonly IValidator<Cliente> _clienteValidator;
        public ClienteController(IClienteRepository clienteRepository, IEmailService emailService, IValidator<Cliente> clienteValidator)
        {
            _clienteRepository = clienteRepository;
            _emailService = emailService;
            _clienteValidator = clienteValidator;
        }

        // GET: ClienteController
        public async Task<ActionResult> Index()
        {
            var clientes = await _clienteRepository.GetAllAsync();
            return View(clientes);
        }

        // GET: ClienteController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var cliente = await _clienteRepository.GetByIdAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // GET: ClienteController/Create
        public async Task<ActionResult> Create()
        {
            var clientes = await _clienteRepository.GetAllAsync();
            ViewBag.Clientes = new SelectList(clientes, "ID_Cliente", "Nombre_Cliente");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Cliente cliente)
        {
            //Validaciones
            ValidationResult validationResult = _clienteValidator.Validate(cliente);

            try
            {
                await _clienteRepository.AddAsync(cliente);

                // Enviar correo electrónico
                string email = cliente.Email_Cliente;
                string subject = "Bienvenido";
                string body = $"Bienvenido a la tienda" + cliente.Nombre_Cliente;

                _emailService.SendEmail(email, cliente.Nombre_Cliente, subject, body);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                validationResult.AddToModelState(this.ModelState);

                return View(cliente);
            }
        }

        // GET: ClienteController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var cliente = await _clienteRepository.GetByIdAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: ClienteController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Cliente cliente)
        {
            var validationResult = _clienteValidator.Validate(cliente);

            try
            {
                await _clienteRepository.EditAsync(cliente);

                return RedirectToAction(nameof(Index));

            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                validationResult.AddToModelState(this.ModelState);

                return View(cliente);
            }
        }

        // GET: ClienteController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var cliente = await _clienteRepository.GetByIdAsync(id);
            if (cliente == null)
            {
                return NotFound();
            }
            return View(cliente);
        }

        // POST: ClienteController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _clienteRepository.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var cliente = await _clienteRepository.GetByIdAsync(id);
                return View("Delete", cliente);
            }
        }
    }
}

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Controllers/ProductoController.cs
using Dapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MiniExcelLibs;
using Tienda_Electronica.Data;
using Tienda_Electronica.Models;
using Tienda_Electronica.Repositories.Categorias;
using Tienda_Electronica.Repositories.Productos;
using Tienda_Electronica.Repositories.Ventas;

namespace Tienda_Electronica.Controllers
{
    [Authorize]
    public class ProductoController : Controller
    {
        //NUEVO---
        private readonly ISqlDataAccess _dataAccess;
        //

        private readonly IProductoRepository _productoRepository;

        //-------------------------
        private readonly ICategoriaRepository _categoriaRepository;
        //-------------------------


        //Validaciones
        //private readonly IValidator<Venta> _validator;   

        public ProductoController(
            IProductoRepository productoRepository,

            //------------
            ICategoriaRepository categoriaRepository,
            //-------------

            //NUEVO ------
            ISqlDataAccess dataAccess
            //


            //IValidator<Venta> validator
            )
        {
            _productoRepository = productoRepository;

            //--------------
            _categoriaRepository = categoriaRepository;
            //--------------

            //Nuevo----
            _dataAccess = dataAccess;
            //

            //_validator = validator;
        }


        // GET: VentaController
        public async Task<ActionResult> Index()
        {
            var producto = await _productoRepository.GetAllAsync();

            return View(producto);
        }

        // GET: VentaController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: VentaController/Create

        // public ActionResult Create()
        public async Task<ActionResult> Create()
        {
            //-------------------
            var categorias = await _categoriaRepository.GetAllAsync();
            ViewBag.Categorias = new SelectList(categorias, "ID_Categoria", "Nombre_Categoria");
            //---------------------------
            return View();
        }

        // POST: VentaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Producto producto)
        {
            try
            {
                await _productoRepository.AddAsync(producto);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                //
                var categorias = await _categoriaRepository.GetAllAsync();
                ViewBag.Categorias = new SelectList(categorias, "ID_Categoria", "Nombre_Categoria");
                //

                return View(producto);
            }
        }

        // GET: VentaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var producto = await _productoRepository.GetByIdAsync(id);

            if (producto == null)
                return NotFound();

            //
            var categorias = await _categoriaRepository.GetAllAsync();
            ViewBag.Categorias = new SelectList(categorias, "ID_Categoria", "Nombre_Categoria", producto.ID_Categoria);
            //

            return View(producto);
        }

        // POST: VentaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Producto producto)
        {
            try
            {
                await _productoRepository.EditAsync(producto);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;

                //
                var categorias = await _categoriaRepository.GetAllAsync();
                ViewBag.Categorias = new SelectList(categorias, "ID_Categoria", "Nombre_Categoria", producto.ID_Categoria);
                //

                return View(producto);
            }
        }

        // GET: VentaController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var producto = await _productoRepository.GetByIdAsync(id);

            if (producto == null)
            {
                return NotFound();
            }

            return View(producto);

        }

        // POST: VentaController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(Producto producto)
        {
            try
            {
                await _productoRepository.DeleteAsync(producto.ID_Producto);

                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                return View(producto);
            }
        }

        //NUEVO
        // GET: ProductoController/ImportData
        [HttpGet]
        public IActionResult ImportData()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> ImportData(IFormFile file)
        {
            var directoryPath = Path.Combine(Directory.GetCurrentDirectory(), "Uploads");

            if (!Directory.Exists(directoryPath))
                Directory.CreateDirectory(directoryPath);

            if (file != null && file.Length > 0)
            {
                var fileName = Path.GetFileName(file.FileName);
                var path = Path.Combine(directoryPath, fileName);

                using (var stream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(stream);
                }

                using (var connection = _dataAccess.GetConnection())
                {
                    using (var stream = System.IO.File.OpenRead(path))
                    {
                        var rows = stream.Query<Producto>();

                        string query = @"INSERT INTO Producto 
                                         VALUES(
                                            @Nombre_Producto,
                                            @Descripcion_Producto,
                                            @PrecioUnitario,
                                            @ID_Categoria)";

                        foreach (var row in rows)
                            connection.Execute(query, new
                            {
                                row.Nombre_Producto,
                                row.Descripcion_Producto,
                                row.PrecioUnitario,
                                row.ID_Categoria
                            });
                    }
                }
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Controllers/VentaController.cs
using FluentValidation;
using FluentValidation.Results;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Tienda_Electronica.Models;
using Tienda_Electronica.Repositories.Clientes;
using Tienda_Electronica.Repositories.Ventas;
using Tienda_Electronica.Validations;

namespace Tienda_Electronica.Controllers
{
    [Authorize]
    public class VentaController : Controller
    {
        private readonly IVentaRepository _ventaRepository;
        private readonly IClienteRepository _clienteRepository;
        private readonly IValidator<Venta> _ventavalidator;

        public VentaController(
            IVentaRepository ventaRepository,
            IClienteRepository clienteRepository,
            IValidator<Venta> ventavalidator
        )
        {
            _ventaRepository = ventaRepository;
            _clienteRepository = clienteRepository;
            _ventavalidator = ventavalidator;
        }

        // GET: VentaController
        public async Task<ActionResult> Index()
        {
            var venta = await _ventaRepository.GetAllAsync();
            return View(venta);
        }

        // GET: VentaController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var venta = await _ventaRepository.GetByIdAsync(id);
            if (venta == null)
                return NotFound();
            return View(venta);
        }

        // GET: VentaController/Create
        public async Task<ActionResult> Create()
        {
            ViewData["ID_Cliente"] = new SelectList(await _clienteRepository.GetAllAsync(), "ID_Cliente", "Nombre_Cliente");
            return View();
        }

        // POST: VentaController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(Venta venta)
        {
            ValidationResult validationResult = _ventavalidator.Validate(venta);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                ViewData["ID_Cliente"] = new SelectList(await _clienteRepository.GetAllAsync(), "ID_Cliente", "Nombre_Cliente", venta.ID_Cliente);
                return View(venta);
            }

            try
            {
                await _ventaRepository.AddAsync(venta);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewData["ID_Cliente"] = new SelectList(await _clienteRepository.GetAllAsync(), "ID_Cliente", "Nombre_Cliente", venta.ID_Cliente);
                return View(venta);
            }
        }

        // GET: VentaController/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var venta = await _ventaRepository.GetByIdAsync(id);
            if (venta == null)
                return NotFound();

            ViewData["ID_Cliente"] = new SelectList(await _clienteRepository.GetAllAsync(), "ID_Cliente", "Nombre_Cliente", venta.ID_Cliente);
            return View(venta);
        }

        // POST: VentaController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Venta venta)
        {
            ValidationResult validationResult = _ventavalidator.Validate(venta);
            if (!validationResult.IsValid)
            {
                validationResult.AddToModelState(this.ModelState);
                ViewData["ID_Cliente"] = new SelectList(await _clienteRepository.GetAllAsync(), "ID_Cliente", "Nombre_Cliente", venta.ID_Cliente);
                return View(venta);
            }

            try
            {
                await _ventaRepository.EditAsync(venta);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                ViewData["ID_Cliente"] = new SelectList(await _clienteRepository.GetAllAsync(), "ID_Cliente", "Nombre_Cliente", venta.ID_Cliente);
                return View(venta);
            }
        }

        // GET: VentaController/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            var venta = await _ventaRepository.GetByIdAsync(id);
            if (venta == null)
                return NotFound();
            return View(venta);
        }

        // POST: VentaController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _ventaRepository.DeleteAsync(id);
                return RedirectToAction(nameof(Index));
            }
            catch (Exception ex)
            {
                ViewBag.Error = ex.Message;
                var venta = await _ventaRepository.GetByIdAsync(id);
                if (venta == null)
                    return NotFound();
                return View(venta);
            }
        }
    }
}

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Views/Shared/Admin/Partials/_Footer.cshtml
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 order-last order-md-first">
                <div class="copyright text-center text-md-start">
                    <p class="text-sm">
                        Diseñado y desarrollado por Grupo #4
                    </p>
                </div>
            </div>
            <!-- end col-->
            <div class="col-md-6">
                <div class="terms d-flex justify-content-center justify-content-md-end">
                    <a href="#0" class="text-sm">Terminos y condiciones</a>
                    <a href="#0" class="text-sm ml-15">Politicas de privacidad</a>
                </div>
            </div>
        </div>
        <!-- end row -->
    </div>
    <!-- end container -->
</footer>

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Views/Shared/Admin/Partials/_Header.cshtml
<header class="header">
    <div class="container-fluid">
        <div class="row">
            <div class="col-lg-5 col-md-5 col-6">
                <div class="header-left d-flex align-items-center">
                    <div class="menu-toggle-btn mr-15">
                        <button id="menu-toggle" class="main-btn primary-btn btn-hover">
                            <i class="lni lni-chevron-left me-2"></i> Menu
                        </button>
                    </div>
                    <div class="header-search d-none d-md-flex">
                        <form action="#">
                            <input type="text" placeholder="Search..." />
                            <button><i class="lni lni-search-alt"></i></button>
                        </form>
                    </div>
                </div>
            </div>
            <div class="col-lg-7 col-md-7 col-6">
                <div class="header-right">
                    <!-- notification start -->
                   
                    <!-- notification end -->
                    <!-- message start -->
                    
                    <!-- message end -->
                    <!-- profile start -->
                    <div class="profile-box ml-15">
                        <button class="dropdown-toggle bg-transparent border-0" type="button" id="profile"
                                data-bs-toggle="dropdown" aria-expanded="false">
                            <div class="profile-info">
                                <div class="info">
                                    <div class="image">
                                        <img src="~/images/Admin.png" alt="" />
                                    </div>
                                    <div>
                                        <h6 class="fw-500">Admin</h6>
                                        <p>Admin</p>
                                    </div>
                                </div>
                            </div>
                        </button>
                        <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="profile">
                            <li>
                                <div class="author-info flex items-center !p-1">
                                    <div class="image">
                                        <img src="~/images/Admin.png" alt="image">
                                    </div>
                                </div>
                            </li>
                            <li class="divider"></li>
                            <li>
                                <form class="d-inline" asp-area="Identity" asp-page="/Account/Manage/Index" method="get">
                                    <button type="submit" class="dropdown-item">
                                        <i class="lni lni-cog"></i> Ajustes
                                    </button>
                                </form>
                            </li>

                            <li class="divider"></li>

                            <li>
                                <form class="d-inline" asp-area="Identity" asp-page="/Account/Logout" method="post">
                                    <button type="submit" class="dropdown-item">
                                        <i class="lni lni-exit"></i> Cerrar sesión
                                    </button>
                                </form>
                            </li>

                        </ul>
                    </div>
                    <!-- profile end -->
                </div>
            </div>
        </div>
    </div>
</header>

Tienda_Electronica/Tienda_Electronica/Tienda_Electronica/Views/Shared/Admin/Partials/_Sidebar.cshtml
<aside class="sidebar-nav-wrapper">
    <div class="navbar-logo text-center">
        <img src="~/images/Logo.png" alt="logo" class="img-fluid rounded" style="max-width: 60px; height: auto;" />
    </div>
    <nav class="sidebar-nav">
        <ul>
            <li class="nav-item">
                <span class="icon">
                    <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M8.74999 18.3333C12.2376 18.3333 15.1364 15.8128 15.7244 12.4941C15.8448 11.8143 15.2737 11.25 14.5833 11.25H9.99999C9.30966 11.25 8.74999 10.6903 8.74999 10V5.41666C8.74999 4.7263 8.18563 4.15512 7.50586 4.27556C4.18711 4.86357 1.66666 7.76243 1.66666 11.25C1.66666 15.162 4.83797 18.3333 8.74999 18.3333Z" />
                        <path d="M17.0833 10C17.7737 10 18.3432 9.43708 18.2408 8.75433C17.7005 5.14918 14.8508 2.29947 11.2457 1.75912C10.5629 1.6568 10 2.2263 10 2.91665V9.16666C10 9.62691 10.3731 10 10.8333 10H17.0833Z" />
                    </svg>
                </span>
            </li>
            <li class="nav-item nav-item-has-children">
                <a href="#0"
                   class=""
                   data-bs-toggle="collapse"
                   data-bs-target="#ddmenu_2"
                   aria-controls="ddmenu_2"
                   aria-expanded="false"
                   aria-label="Toggle navigation">
                    <span class="icon">
                        <svg width="20" height="20" viewBox="0 0 20 20" fill="none" xmlns="http://www.w3.org/2000/svg">
                            <path d="M11.8097 1.66667C11.8315 1.66667 11.8533 1.6671 11.875 1.66796V4.16667C11.875 5.43232 12.901 6.45834 14.1667 6.45834H16.6654C16.6663 6.48007 16.6667 6.50186 16.6667 6.5237V16.6667C16.6667 17.5872 15.9205 18.3333 15 18.3333H5.00001C4.07954 18.3333 3.33334 17.5872 3.33334 16.6667V3.33334C3.33334 2.41286 4.07954 1.66667 5.00001 1.66667H11.8097ZM6.66668 7.70834C6.3215 7.70834 6.04168 7.98816 6.04168 8.33334C6.04168 8.67851 6.3215 8.95834 6.66668 8.95834H10C10.3452 8.95834 10.625 8.67851 10.625 8.33334C10.625 7.98816 10.3452 7.70834 10 7.70834H6.66668ZM6.04168 11.6667C6.04168 12.0118 6.3215 12.2917 6.66668 12.2917H13.3333C13.6785 12.2917 13.9583 12.0118 13.9583 11.6667C13.9583 11.3215 13.6785 11.0417 13.3333 11.0417H6.66668C6.3215 11.0417 6.04168 11.3215 6.04168 11.6667ZM6.66668 14.375C6.3215 14.375 6.04168 14.6548 6.04168 15C6.04168 15.3452 6.3215 15.625 6.66668 15.625H13.3333C13.6785 15.625 13.9583 15.3452 13.9583 15C13.9583 14.6548 13.6785 14.375 13.3333 14.375H6.66668Z" />
                            <path d="M13.125 2.29167L16.0417 5.20834H14.1667C13.5913 5.20834 13.125 4.74197 13.125 4.16667V2.29167Z" />
                        </svg>
                    </span>
                    <span class="text">Administracion</span>
                </a>
                <ul id="ddmenu_2" class="collapse show dropdown-nav">
                    <li>
                        <a asp-controller="Categoria" asp-action="Index"> Categorias </a>
                    </li>
                    <li>
                        <a asp-controller="Inventario" asp-action="Index"> Inventario </a>
                    </li>
                    <li>
                        <a asp-controller="Cliente" asp-action="Index"> Clientes </a>
                    </li>
                    <li>
                        <a asp-controller="Producto" asp-action="Index"> Productos </a>
                    </li>
                    <li>
                        <a asp-controller="DetalleVenta" asp-action="Index"> Detalles ventas </a>
                    </li>
                    <li>
                        <a asp-controller="Venta" asp-action="Index"> Venta </a>
                    </li>
                </ul>
            </li>
        </ul>
    </nav>
</aside>